# Generated by Django 3.1.1 on 2020-09-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('img', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=30, null=True)),
                ('categoria', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('completado', models.BooleanField()),
            ],
        ),
    ]
